// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: manifest/protobuf/camera/v1/camera.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CameraRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId uint64     `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AgentId  uint64     `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name     string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Ext      *CameraExt `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`
	Time     uint64     `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	ErrMsg   string     `protobuf:"bytes,6,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Channels []*Channel `protobuf:"bytes,7,rep,name=channels,proto3" json:"channels,omitempty"`
}

func (x *CameraRequest) Reset() {
	*x = CameraRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_camera_v1_camera_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraRequest) ProtoMessage() {}

func (x *CameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_camera_v1_camera_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraRequest.ProtoReflect.Descriptor instead.
func (*CameraRequest) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_camera_v1_camera_proto_rawDescGZIP(), []int{0}
}

func (x *CameraRequest) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *CameraRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *CameraRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CameraRequest) GetExt() *CameraExt {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *CameraRequest) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CameraRequest) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *CameraRequest) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type Channel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url       string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Type      string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Channel) Reset() {
	*x = Channel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_camera_v1_camera_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_camera_v1_camera_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_camera_v1_camera_proto_rawDescGZIP(), []int{1}
}

func (x *Channel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Channel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CameraExt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manufacturer string `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"` // 生产厂商
	Model        string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`               // 型号
	Firmware     string `protobuf:"bytes,3,opt,name=firmware,proto3" json:"firmware,omitempty"`         // 固件版本
	Name         string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                 // 设备名
	SerialNumber string `protobuf:"bytes,5,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	HardwareId   string `protobuf:"bytes,6,opt,name=hardwareId,proto3" json:"hardwareId,omitempty"`
}

func (x *CameraExt) Reset() {
	*x = CameraExt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_camera_v1_camera_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CameraExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraExt) ProtoMessage() {}

func (x *CameraExt) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_camera_v1_camera_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraExt.ProtoReflect.Descriptor instead.
func (*CameraExt) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_camera_v1_camera_proto_rawDescGZIP(), []int{2}
}

func (x *CameraExt) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *CameraExt) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CameraExt) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *CameraExt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CameraExt) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CameraExt) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

type CameraResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CameraResponse) Reset() {
	*x = CameraResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_camera_v1_camera_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraResponse) ProtoMessage() {}

func (x *CameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_camera_v1_camera_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraResponse.ProtoReflect.Descriptor instead.
func (*CameraResponse) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_camera_v1_camera_proto_rawDescGZIP(), []int{3}
}

func (x *CameraResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CameraData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request []*CameraRequest `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
}

func (x *CameraData) Reset() {
	*x = CameraData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_camera_v1_camera_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CameraData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraData) ProtoMessage() {}

func (x *CameraData) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_camera_v1_camera_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraData.ProtoReflect.Descriptor instead.
func (*CameraData) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_camera_v1_camera_proto_rawDescGZIP(), []int{4}
}

func (x *CameraData) GetRequest() []*CameraRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

var File_manifest_protobuf_camera_v1_camera_proto protoreflect.FileDescriptor

var file_manifest_protobuf_camera_v1_camera_proto_rawDesc = []byte{
	0x0a, 0x28, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x2e, 0x76, 0x31, 0x22, 0xdf, 0x01, 0x0a, 0x0d, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x45, 0x78, 0x74, 0x52, 0x03, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x2e, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x08, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x22, 0x62, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xb9, 0x01, 0x0a, 0x09,
	0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x45, 0x78, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e,
	0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x61, 0x72,
	0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x40, 0x0a,
	0x0a, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32,
	0x4d, 0x0a, 0x0d, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3c, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x2e, 0x63, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x19, 0x2e, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b,
	0x5a, 0x09, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_manifest_protobuf_camera_v1_camera_proto_rawDescOnce sync.Once
	file_manifest_protobuf_camera_v1_camera_proto_rawDescData = file_manifest_protobuf_camera_v1_camera_proto_rawDesc
)

func file_manifest_protobuf_camera_v1_camera_proto_rawDescGZIP() []byte {
	file_manifest_protobuf_camera_v1_camera_proto_rawDescOnce.Do(func() {
		file_manifest_protobuf_camera_v1_camera_proto_rawDescData = protoimpl.X.CompressGZIP(file_manifest_protobuf_camera_v1_camera_proto_rawDescData)
	})
	return file_manifest_protobuf_camera_v1_camera_proto_rawDescData
}

var file_manifest_protobuf_camera_v1_camera_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_manifest_protobuf_camera_v1_camera_proto_goTypes = []interface{}{
	(*CameraRequest)(nil),  // 0: camera.v1.CameraRequest
	(*Channel)(nil),        // 1: camera.v1.Channel
	(*CameraExt)(nil),      // 2: camera.v1.CameraExt
	(*CameraResponse)(nil), // 3: camera.v1.CameraResponse
	(*CameraData)(nil),     // 4: camera.v1.CameraData
}
var file_manifest_protobuf_camera_v1_camera_proto_depIdxs = []int32{
	2, // 0: camera.v1.CameraRequest.ext:type_name -> camera.v1.CameraExt
	1, // 1: camera.v1.CameraRequest.channels:type_name -> camera.v1.Channel
	0, // 2: camera.v1.CameraData.request:type_name -> camera.v1.CameraRequest
	4, // 3: camera.v1.CameraService.Report:input_type -> camera.v1.CameraData
	3, // 4: camera.v1.CameraService.Report:output_type -> camera.v1.CameraResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_manifest_protobuf_camera_v1_camera_proto_init() }
func file_manifest_protobuf_camera_v1_camera_proto_init() {
	if File_manifest_protobuf_camera_v1_camera_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_manifest_protobuf_camera_v1_camera_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CameraRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_camera_v1_camera_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Channel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_camera_v1_camera_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CameraExt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_camera_v1_camera_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CameraResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_camera_v1_camera_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CameraData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_manifest_protobuf_camera_v1_camera_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manifest_protobuf_camera_v1_camera_proto_goTypes,
		DependencyIndexes: file_manifest_protobuf_camera_v1_camera_proto_depIdxs,
		MessageInfos:      file_manifest_protobuf_camera_v1_camera_proto_msgTypes,
	}.Build()
	File_manifest_protobuf_camera_v1_camera_proto = out.File
	file_manifest_protobuf_camera_v1_camera_proto_rawDesc = nil
	file_manifest_protobuf_camera_v1_camera_proto_goTypes = nil
	file_manifest_protobuf_camera_v1_camera_proto_depIdxs = nil
}
