// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: manifest/protobuf/daemonize/v1/controller.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentCmd int32

const (
	AgentCmd_NoneCmd AgentCmd = 0
	AgentCmd_Start   AgentCmd = 1
	AgentCmd_Stop    AgentCmd = 2
)

// Enum value maps for AgentCmd.
var (
	AgentCmd_name = map[int32]string{
		0: "NoneCmd",
		1: "Start",
		2: "Stop",
	}
	AgentCmd_value = map[string]int32{
		"NoneCmd": 0,
		"Start":   1,
		"Stop":    2,
	}
)

func (x AgentCmd) Enum() *AgentCmd {
	p := new(AgentCmd)
	*p = x
	return p
}

func (x AgentCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_manifest_protobuf_daemonize_v1_controller_proto_enumTypes[0].Descriptor()
}

func (AgentCmd) Type() protoreflect.EnumType {
	return &file_manifest_protobuf_daemonize_v1_controller_proto_enumTypes[0]
}

func (x AgentCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentCmd.Descriptor instead.
func (AgentCmd) EnumDescriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{0}
}

type ProcessState int32

const (
	ProcessState_NoneState ProcessState = 0
	ProcessState_Running   ProcessState = 1
	ProcessState_Stopped   ProcessState = 2
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "NoneState",
		1: "Running",
		2: "Stopped",
	}
	ProcessState_value = map[string]int32{
		"NoneState": 0,
		"Running":   1,
		"Stopped":   2,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_manifest_protobuf_daemonize_v1_controller_proto_enumTypes[1].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_manifest_protobuf_daemonize_v1_controller_proto_enumTypes[1]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{1}
}

type AgentOperateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId uint64 `protobuf:"varint,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
}

func (x *AgentOperateReq) Reset() {
	*x = AgentOperateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentOperateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOperateReq) ProtoMessage() {}

func (x *AgentOperateReq) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOperateReq.ProtoReflect.Descriptor instead.
func (*AgentOperateReq) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{0}
}

func (x *AgentOperateReq) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type AgentOperateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"` // 返回码
	// 操作进程
	Cmd   AgentCmd `protobuf:"varint,2,opt,name=Cmd,proto3,enum=daemonize.grpc.v1.AgentCmd" json:"Cmd,omitempty"`
	Names []string `protobuf:"bytes,3,rep,name=Names,proto3" json:"Names,omitempty"`
}

func (x *AgentOperateRes) Reset() {
	*x = AgentOperateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentOperateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOperateRes) ProtoMessage() {}

func (x *AgentOperateRes) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOperateRes.ProtoReflect.Descriptor instead.
func (*AgentOperateRes) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{1}
}

func (x *AgentOperateRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AgentOperateRes) GetCmd() AgentCmd {
	if x != nil {
		return x.Cmd
	}
	return AgentCmd_NoneCmd
}

func (x *AgentOperateRes) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type AgentRegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId uint64 `protobuf:"varint,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Version  string `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Ipv4     string `protobuf:"bytes,4,opt,name=ipv4,proto3" json:"ipv4,omitempty"` // 主机的内网IPv4地址
	Ipv6     string `protobuf:"bytes,5,opt,name=ipv6,proto3" json:"ipv6,omitempty"` // 主机的内网IPv6地址
}

func (x *AgentRegisterReq) Reset() {
	*x = AgentRegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegisterReq) ProtoMessage() {}

func (x *AgentRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegisterReq.ProtoReflect.Descriptor instead.
func (*AgentRegisterReq) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{2}
}

func (x *AgentRegisterReq) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *AgentRegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentRegisterReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentRegisterReq) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *AgentRegisterReq) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

type AgentRegisterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigUuid string `protobuf:"bytes,1,opt,name=ConfigUuid,proto3" json:"ConfigUuid,omitempty"`
}

func (x *AgentRegisterRes) Reset() {
	*x = AgentRegisterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentRegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegisterRes) ProtoMessage() {}

func (x *AgentRegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegisterRes.ProtoReflect.Descriptor instead.
func (*AgentRegisterRes) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{3}
}

func (x *AgentRegisterRes) GetConfigUuid() string {
	if x != nil {
		return x.ConfigUuid
	}
	return ""
}

type AgentUnregisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId uint64 `protobuf:"varint,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
}

func (x *AgentUnregisterReq) Reset() {
	*x = AgentUnregisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentUnregisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUnregisterReq) ProtoMessage() {}

func (x *AgentUnregisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUnregisterReq.ProtoReflect.Descriptor instead.
func (*AgentUnregisterReq) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{4}
}

func (x *AgentUnregisterReq) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type AgentUnregisterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AgentUnregisterRes) Reset() {
	*x = AgentUnregisterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentUnregisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUnregisterRes) ProtoMessage() {}

func (x *AgentUnregisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUnregisterRes.ProtoReflect.Descriptor instead.
func (*AgentUnregisterRes) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{5}
}

type AgentProcessInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessList []*ProcessInfo `protobuf:"bytes,5,rep,name=ProcessList,proto3" json:"ProcessList,omitempty"` // 进程列表
}

func (x *AgentProcessInfo) Reset() {
	*x = AgentProcessInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProcessInfo) ProtoMessage() {}

func (x *AgentProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProcessInfo.ProtoReflect.Descriptor instead.
func (*AgentProcessInfo) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{6}
}

func (x *AgentProcessInfo) GetProcessList() []*ProcessInfo {
	if x != nil {
		return x.ProcessList
	}
	return nil
}

type ProcessInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                                        // 进程名字
	State     ProcessState           `protobuf:"varint,2,opt,name=State,proto3,enum=daemonize.grpc.v1.ProcessState" json:"State,omitempty"` // 进程状态
	Version   string                 `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`                                  // 进程版本号
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`                              // 启动时间
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetState() ProcessState {
	if x != nil {
		return x.State
	}
	return ProcessState_NoneState
}

func (x *ProcessInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProcessInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type AgentHeartbeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId         uint64            `protobuf:"varint,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`                // agent 的id
	Name             string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                         // agent 的名字
	Version          string            `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`                   // agent 的版本
	ConfigUuid       string            `protobuf:"bytes,4,opt,name=ConfigUuid,proto3" json:"ConfigUuid,omitempty"`             // agent 的配置版本
	AgentProcessInfo *AgentProcessInfo `protobuf:"bytes,5,opt,name=AgentProcessInfo,proto3" json:"AgentProcessInfo,omitempty"` // 进程列表
}

func (x *AgentHeartbeatReq) Reset() {
	*x = AgentHeartbeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeatReq) ProtoMessage() {}

func (x *AgentHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeatReq.ProtoReflect.Descriptor instead.
func (*AgentHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{8}
}

func (x *AgentHeartbeatReq) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *AgentHeartbeatReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentHeartbeatReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentHeartbeatReq) GetConfigUuid() string {
	if x != nil {
		return x.ConfigUuid
	}
	return ""
}

func (x *AgentHeartbeatReq) GetAgentProcessInfo() *AgentProcessInfo {
	if x != nil {
		return x.AgentProcessInfo
	}
	return nil
}

type AgentHeartbeatRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 配置uuid
	ConfigUuid string `protobuf:"bytes,3,opt,name=ConfigUuid,proto3" json:"ConfigUuid,omitempty"`
}

func (x *AgentHeartbeatRes) Reset() {
	*x = AgentHeartbeatRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentHeartbeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeatRes) ProtoMessage() {}

func (x *AgentHeartbeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeatRes.ProtoReflect.Descriptor instead.
func (*AgentHeartbeatRes) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{9}
}

func (x *AgentHeartbeatRes) GetConfigUuid() string {
	if x != nil {
		return x.ConfigUuid
	}
	return ""
}

type AgentGetConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigUuid string `protobuf:"bytes,1,opt,name=ConfigUuid,proto3" json:"ConfigUuid,omitempty"`
}

func (x *AgentGetConfigReq) Reset() {
	*x = AgentGetConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentGetConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentGetConfigReq) ProtoMessage() {}

func (x *AgentGetConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentGetConfigReq.ProtoReflect.Descriptor instead.
func (*AgentGetConfigReq) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{10}
}

func (x *AgentGetConfigReq) GetConfigUuid() string {
	if x != nil {
		return x.ConfigUuid
	}
	return ""
}

type AgentGetConfigRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *AgentGetConfigRes) Reset() {
	*x = AgentGetConfigRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentGetConfigRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentGetConfigRes) ProtoMessage() {}

func (x *AgentGetConfigRes) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentGetConfigRes.ProtoReflect.Descriptor instead.
func (*AgentGetConfigRes) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{11}
}

func (x *AgentGetConfigRes) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AgentUpdateConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectIdList []uint64 `protobuf:"varint,1,rep,packed,name=ObjectIdList,proto3" json:"ObjectIdList,omitempty"`
	ConfigUuid   string   `protobuf:"bytes,2,opt,name=ConfigUuid,proto3" json:"ConfigUuid,omitempty"`
}

func (x *AgentUpdateConfigReq) Reset() {
	*x = AgentUpdateConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentUpdateConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdateConfigReq) ProtoMessage() {}

func (x *AgentUpdateConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpdateConfigReq.ProtoReflect.Descriptor instead.
func (*AgentUpdateConfigReq) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{12}
}

func (x *AgentUpdateConfigReq) GetObjectIdList() []uint64 {
	if x != nil {
		return x.ObjectIdList
	}
	return nil
}

func (x *AgentUpdateConfigReq) GetConfigUuid() string {
	if x != nil {
		return x.ConfigUuid
	}
	return ""
}

type AgentUpdateConfigRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AgentUpdateConfigRes) Reset() {
	*x = AgentUpdateConfigRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentUpdateConfigRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdateConfigRes) ProtoMessage() {}

func (x *AgentUpdateConfigRes) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpdateConfigRes.ProtoReflect.Descriptor instead.
func (*AgentUpdateConfigRes) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{13}
}

type ProcessOperateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentObjectId uint64   `protobuf:"varint,1,opt,name=AgentObjectId,proto3" json:"AgentObjectId,omitempty"`
	Names         []string `protobuf:"bytes,2,rep,name=Names,proto3" json:"Names,omitempty"`
}

func (x *ProcessOperateInfo) Reset() {
	*x = ProcessOperateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessOperateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOperateInfo) ProtoMessage() {}

func (x *ProcessOperateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOperateInfo.ProtoReflect.Descriptor instead.
func (*ProcessOperateInfo) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessOperateInfo) GetAgentObjectId() uint64 {
	if x != nil {
		return x.AgentObjectId
	}
	return 0
}

func (x *ProcessOperateInfo) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type AgentOperateProcessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd             AgentCmd              `protobuf:"varint,1,opt,name=cmd,proto3,enum=daemonize.grpc.v1.AgentCmd" json:"cmd,omitempty"`
	OperateInfoList []*ProcessOperateInfo `protobuf:"bytes,2,rep,name=OperateInfoList,proto3" json:"OperateInfoList,omitempty"`
}

func (x *AgentOperateProcessReq) Reset() {
	*x = AgentOperateProcessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentOperateProcessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOperateProcessReq) ProtoMessage() {}

func (x *AgentOperateProcessReq) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOperateProcessReq.ProtoReflect.Descriptor instead.
func (*AgentOperateProcessReq) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{15}
}

func (x *AgentOperateProcessReq) GetCmd() AgentCmd {
	if x != nil {
		return x.Cmd
	}
	return AgentCmd_NoneCmd
}

func (x *AgentOperateProcessReq) GetOperateInfoList() []*ProcessOperateInfo {
	if x != nil {
		return x.OperateInfoList
	}
	return nil
}

type AgentOperateProcessRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AgentOperateProcessRes) Reset() {
	*x = AgentOperateProcessRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentOperateProcessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOperateProcessRes) ProtoMessage() {}

func (x *AgentOperateProcessRes) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOperateProcessRes.ProtoReflect.Descriptor instead.
func (*AgentOperateProcessRes) Descriptor() ([]byte, []int) {
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP(), []int{16}
}

var File_manifest_protobuf_daemonize_v1_controller_proto protoreflect.FileDescriptor

var file_manifest_protobuf_daemonize_v1_controller_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x22, 0x6a, 0x0a, 0x0f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x03, 0x43,
	0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x43, 0x6d, 0x64, 0x52, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x22, 0x84, 0x01, 0x0a, 0x10, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x70, 0x76, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x36, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x69, 0x70, 0x76, 0x36, 0x22, 0x32, 0x0a, 0x10, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x75, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x12, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x14, 0x0a,
	0x12, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x10, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x40, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xac, 0x01, 0x0a, 0x0b, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x64,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x38,
	0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xce, 0x01, 0x0a, 0x11, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x55, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x55, 0x75, 0x69, 0x64, 0x12, 0x4f, 0x0a, 0x10, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x10, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x33, 0x0a, 0x11, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x75, 0x69, 0x64, 0x22, 0x33,
	0x0a, 0x11, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55,
	0x75, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x14, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x0c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x75, 0x69, 0x64, 0x22, 0x16,
	0x0a, 0x14, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x22, 0x50, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x0d,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x16, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1b, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x52, 0x03, 0x63,
	0x6d, 0x64, 0x12, 0x4f, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x2a, 0x2c, 0x0a,
	0x08, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x6e,
	0x65, 0x43, 0x6d, 0x64, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x10, 0x02, 0x2a, 0x37, 0x0a, 0x0c, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x4e,
	0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x75,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x70,
	0x65, 0x64, 0x10, 0x02, 0x32, 0xe3, 0x04, 0x0a, 0x16, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5b, 0x0a, 0x0d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x23, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a,
	0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x0f,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x25, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69,
	0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x5e, 0x0a, 0x0e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x12, 0x24, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x5a, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12,
	0x22, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x5e, 0x0a, 0x0e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x2e,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x13, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x29, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_manifest_protobuf_daemonize_v1_controller_proto_rawDescOnce sync.Once
	file_manifest_protobuf_daemonize_v1_controller_proto_rawDescData = file_manifest_protobuf_daemonize_v1_controller_proto_rawDesc
)

func file_manifest_protobuf_daemonize_v1_controller_proto_rawDescGZIP() []byte {
	file_manifest_protobuf_daemonize_v1_controller_proto_rawDescOnce.Do(func() {
		file_manifest_protobuf_daemonize_v1_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_manifest_protobuf_daemonize_v1_controller_proto_rawDescData)
	})
	return file_manifest_protobuf_daemonize_v1_controller_proto_rawDescData
}

var file_manifest_protobuf_daemonize_v1_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_manifest_protobuf_daemonize_v1_controller_proto_goTypes = []interface{}{
	(AgentCmd)(0),                  // 0: daemonize.grpc.v1.AgentCmd
	(ProcessState)(0),              // 1: daemonize.grpc.v1.ProcessState
	(*AgentOperateReq)(nil),        // 2: daemonize.grpc.v1.AgentOperateReq
	(*AgentOperateRes)(nil),        // 3: daemonize.grpc.v1.AgentOperateRes
	(*AgentRegisterReq)(nil),       // 4: daemonize.grpc.v1.AgentRegisterReq
	(*AgentRegisterRes)(nil),       // 5: daemonize.grpc.v1.AgentRegisterRes
	(*AgentUnregisterReq)(nil),     // 6: daemonize.grpc.v1.AgentUnregisterReq
	(*AgentUnregisterRes)(nil),     // 7: daemonize.grpc.v1.AgentUnregisterRes
	(*AgentProcessInfo)(nil),       // 8: daemonize.grpc.v1.AgentProcessInfo
	(*ProcessInfo)(nil),            // 9: daemonize.grpc.v1.ProcessInfo
	(*AgentHeartbeatReq)(nil),      // 10: daemonize.grpc.v1.AgentHeartbeatReq
	(*AgentHeartbeatRes)(nil),      // 11: daemonize.grpc.v1.AgentHeartbeatRes
	(*AgentGetConfigReq)(nil),      // 12: daemonize.grpc.v1.AgentGetConfigReq
	(*AgentGetConfigRes)(nil),      // 13: daemonize.grpc.v1.AgentGetConfigRes
	(*AgentUpdateConfigReq)(nil),   // 14: daemonize.grpc.v1.AgentUpdateConfigReq
	(*AgentUpdateConfigRes)(nil),   // 15: daemonize.grpc.v1.AgentUpdateConfigRes
	(*ProcessOperateInfo)(nil),     // 16: daemonize.grpc.v1.ProcessOperateInfo
	(*AgentOperateProcessReq)(nil), // 17: daemonize.grpc.v1.AgentOperateProcessReq
	(*AgentOperateProcessRes)(nil), // 18: daemonize.grpc.v1.AgentOperateProcessRes
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
}
var file_manifest_protobuf_daemonize_v1_controller_proto_depIdxs = []int32{
	0,  // 0: daemonize.grpc.v1.AgentOperateRes.Cmd:type_name -> daemonize.grpc.v1.AgentCmd
	9,  // 1: daemonize.grpc.v1.AgentProcessInfo.ProcessList:type_name -> daemonize.grpc.v1.ProcessInfo
	1,  // 2: daemonize.grpc.v1.ProcessInfo.State:type_name -> daemonize.grpc.v1.ProcessState
	19, // 3: daemonize.grpc.v1.ProcessInfo.StartTime:type_name -> google.protobuf.Timestamp
	8,  // 4: daemonize.grpc.v1.AgentHeartbeatReq.AgentProcessInfo:type_name -> daemonize.grpc.v1.AgentProcessInfo
	0,  // 5: daemonize.grpc.v1.AgentOperateProcessReq.cmd:type_name -> daemonize.grpc.v1.AgentCmd
	16, // 6: daemonize.grpc.v1.AgentOperateProcessReq.OperateInfoList:type_name -> daemonize.grpc.v1.ProcessOperateInfo
	4,  // 7: daemonize.grpc.v1.AgentControllerService.AgentRegister:input_type -> daemonize.grpc.v1.AgentRegisterReq
	6,  // 8: daemonize.grpc.v1.AgentControllerService.AgentUnregister:input_type -> daemonize.grpc.v1.AgentUnregisterReq
	10, // 9: daemonize.grpc.v1.AgentControllerService.AgentHeartbeat:input_type -> daemonize.grpc.v1.AgentHeartbeatReq
	2,  // 10: daemonize.grpc.v1.AgentControllerService.AgentOperate:input_type -> daemonize.grpc.v1.AgentOperateReq
	12, // 11: daemonize.grpc.v1.AgentControllerService.AgentGetConfig:input_type -> daemonize.grpc.v1.AgentGetConfigReq
	17, // 12: daemonize.grpc.v1.AgentControllerService.AgentOperateProcess:input_type -> daemonize.grpc.v1.AgentOperateProcessReq
	5,  // 13: daemonize.grpc.v1.AgentControllerService.AgentRegister:output_type -> daemonize.grpc.v1.AgentRegisterRes
	7,  // 14: daemonize.grpc.v1.AgentControllerService.AgentUnregister:output_type -> daemonize.grpc.v1.AgentUnregisterRes
	11, // 15: daemonize.grpc.v1.AgentControllerService.AgentHeartbeat:output_type -> daemonize.grpc.v1.AgentHeartbeatRes
	3,  // 16: daemonize.grpc.v1.AgentControllerService.AgentOperate:output_type -> daemonize.grpc.v1.AgentOperateRes
	13, // 17: daemonize.grpc.v1.AgentControllerService.AgentGetConfig:output_type -> daemonize.grpc.v1.AgentGetConfigRes
	18, // 18: daemonize.grpc.v1.AgentControllerService.AgentOperateProcess:output_type -> daemonize.grpc.v1.AgentOperateProcessRes
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_manifest_protobuf_daemonize_v1_controller_proto_init() }
func file_manifest_protobuf_daemonize_v1_controller_proto_init() {
	if File_manifest_protobuf_daemonize_v1_controller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentOperateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentOperateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentRegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentRegisterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentUnregisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentUnregisterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentProcessInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentHeartbeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentHeartbeatRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentGetConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentGetConfigRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentUpdateConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentUpdateConfigRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessOperateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentOperateProcessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentOperateProcessRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_manifest_protobuf_daemonize_v1_controller_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manifest_protobuf_daemonize_v1_controller_proto_goTypes,
		DependencyIndexes: file_manifest_protobuf_daemonize_v1_controller_proto_depIdxs,
		EnumInfos:         file_manifest_protobuf_daemonize_v1_controller_proto_enumTypes,
		MessageInfos:      file_manifest_protobuf_daemonize_v1_controller_proto_msgTypes,
	}.Build()
	File_manifest_protobuf_daemonize_v1_controller_proto = out.File
	file_manifest_protobuf_daemonize_v1_controller_proto_rawDesc = nil
	file_manifest_protobuf_daemonize_v1_controller_proto_goTypes = nil
	file_manifest_protobuf_daemonize_v1_controller_proto_depIdxs = nil
}
