// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: manifest/protobuf/metric/v1/server.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DeviceReportService_ReportDeviceInfo_FullMethodName  = "/metric.grpc.v1.DeviceReportService/ReportDeviceInfo"
	DeviceReportService_ReportTimeData_FullMethodName    = "/metric.grpc.v1.DeviceReportService/ReportTimeData"
	DeviceReportService_ReportScheduleLog_FullMethodName = "/metric.grpc.v1.DeviceReportService/ReportScheduleLog"
)

// DeviceReportServiceClient is the client API for DeviceReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceReportServiceClient interface {
	// 更新容器信息
	ReportDeviceInfo(ctx context.Context, in *ExportMetricsServiceRequest, opts ...grpc.CallOption) (*NodeRes, error)
	// 更新时序数据
	ReportTimeData(ctx context.Context, in *ExportTimeDataRequest, opts ...grpc.CallOption) (*NodeRes, error)
	// 更新控制日志
	ReportScheduleLog(ctx context.Context, in *ExportControlLogRequest, opts ...grpc.CallOption) (*NodeRes, error)
}

type deviceReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceReportServiceClient(cc grpc.ClientConnInterface) DeviceReportServiceClient {
	return &deviceReportServiceClient{cc}
}

func (c *deviceReportServiceClient) ReportDeviceInfo(ctx context.Context, in *ExportMetricsServiceRequest, opts ...grpc.CallOption) (*NodeRes, error) {
	out := new(NodeRes)
	err := c.cc.Invoke(ctx, DeviceReportService_ReportDeviceInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceReportServiceClient) ReportTimeData(ctx context.Context, in *ExportTimeDataRequest, opts ...grpc.CallOption) (*NodeRes, error) {
	out := new(NodeRes)
	err := c.cc.Invoke(ctx, DeviceReportService_ReportTimeData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceReportServiceClient) ReportScheduleLog(ctx context.Context, in *ExportControlLogRequest, opts ...grpc.CallOption) (*NodeRes, error) {
	out := new(NodeRes)
	err := c.cc.Invoke(ctx, DeviceReportService_ReportScheduleLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceReportServiceServer is the server API for DeviceReportService service.
// All implementations must embed UnimplementedDeviceReportServiceServer
// for forward compatibility
type DeviceReportServiceServer interface {
	// 更新容器信息
	ReportDeviceInfo(context.Context, *ExportMetricsServiceRequest) (*NodeRes, error)
	// 更新时序数据
	ReportTimeData(context.Context, *ExportTimeDataRequest) (*NodeRes, error)
	// 更新控制日志
	ReportScheduleLog(context.Context, *ExportControlLogRequest) (*NodeRes, error)
	mustEmbedUnimplementedDeviceReportServiceServer()
}

// UnimplementedDeviceReportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceReportServiceServer struct {
}

func (UnimplementedDeviceReportServiceServer) ReportDeviceInfo(context.Context, *ExportMetricsServiceRequest) (*NodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportDeviceInfo not implemented")
}
func (UnimplementedDeviceReportServiceServer) ReportTimeData(context.Context, *ExportTimeDataRequest) (*NodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTimeData not implemented")
}
func (UnimplementedDeviceReportServiceServer) ReportScheduleLog(context.Context, *ExportControlLogRequest) (*NodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportScheduleLog not implemented")
}
func (UnimplementedDeviceReportServiceServer) mustEmbedUnimplementedDeviceReportServiceServer() {}

// UnsafeDeviceReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceReportServiceServer will
// result in compilation errors.
type UnsafeDeviceReportServiceServer interface {
	mustEmbedUnimplementedDeviceReportServiceServer()
}

func RegisterDeviceReportServiceServer(s grpc.ServiceRegistrar, srv DeviceReportServiceServer) {
	s.RegisterService(&DeviceReportService_ServiceDesc, srv)
}

func _DeviceReportService_ReportDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportMetricsServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceReportServiceServer).ReportDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceReportService_ReportDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceReportServiceServer).ReportDeviceInfo(ctx, req.(*ExportMetricsServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceReportService_ReportTimeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportTimeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceReportServiceServer).ReportTimeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceReportService_ReportTimeData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceReportServiceServer).ReportTimeData(ctx, req.(*ExportTimeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceReportService_ReportScheduleLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportControlLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceReportServiceServer).ReportScheduleLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceReportService_ReportScheduleLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceReportServiceServer).ReportScheduleLog(ctx, req.(*ExportControlLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceReportService_ServiceDesc is the grpc.ServiceDesc for DeviceReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metric.grpc.v1.DeviceReportService",
	HandlerType: (*DeviceReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportDeviceInfo",
			Handler:    _DeviceReportService_ReportDeviceInfo_Handler,
		},
		{
			MethodName: "ReportTimeData",
			Handler:    _DeviceReportService_ReportTimeData_Handler,
		},
		{
			MethodName: "ReportScheduleLog",
			Handler:    _DeviceReportService_ReportScheduleLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manifest/protobuf/metric/v1/server.proto",
}
